colonialismdb/population/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('colonialismdb.population.views',
    # Example:
    # (r'^colonialismdb/', include('colonialismdb.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^query/download$', 'download_data'),
    (r'^query/', 'query'),
    (r'^$', 'index'),
)

colonialismdb/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin, databrowse
admin.autodiscover()

from django.contrib.auth.decorators import login_required

from common.models import Location, Religion, Ethnicity, Race, EthnicOrigin
from population.models import MainDataEntry
from common.models import *

databrowse.site.register(Location)
databrowse.site.register(Religion)
databrowse.site.register(Ethnicity)
databrowse.site.register(Race)
databrowse.site.register(EthnicOrigin)
databrowse.site.register(MainDataEntry)

urlpatterns = patterns('',
    # Example:
    # (r'^colonialismdb/', include('colonialismdb.foo.urls')),

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^about/$','common.views.about', name='about'),
    url(r'^$','common.views.index', name='index'),
    url(r'^search/$','common.views.search', name='search'),
    url(r'^economics/$','economics.views.econsearch', name='economics'),
    url(r'^education/$','education.views.edusearch', name='education'),
    url(r'^politics/$','government.views.govtsearch', name='government'),
    url(r'^population/$','population.views.popsearch', name='population'),
    url(r'^infrastructure/$','infrastructure.views.infrasearch', name='infrastructure'),
    url(r'^sourceinfo/$','sources.views.sourceinfo', name='sourceinfo'),

    #(r'^testing$','economics.views.testing'),

    #(r'^population/', include('colonialismdb.population.urls')),
    # registration
    (r'^accounts/', include('registration.backends.default.urls')),


    (r'^government/locationlookup/$', 'government.views.locationlookup'),
    (r'^economics/locationlookup/$', 'economics.views.locationlookup'),
    (r'^education/locationlookup/$', 'education.views.locationlookup'),
    (r'^population/locationlookup/$', 'population.views.locationlookup'),
    (r'^infrastructure/locationlookup/$', 'infrastructure.views.locationlookup'),

    (r'^test/(?P<from_applabel>[^/]+)/(?P<from_model>[^/]+)/((add)|(\d+))/autocomplete/(?P<to_applabel>[^/]+)/(?P<to_model>[^/]+)/$', 'colonialismdb.common.views.autocomplete'),
    (r'^test/(?P<from_applabel>[^/]+)/(?P<from_model>[^/]+)/(?P<from_id>\d+)/get_label/(?P<to_applabel>[^/]+)/(?P<to_model>[^/]+)/$', 'colonialismdb.common.views.get_label'),

    (r'^admin/merge_selected/', 'colonialismdb.common.admin.merge_selected'),
    (r'^admin/(?P<from_applabel>[^/]+)/(?P<from_model>[^/]+)/((add)|(\d+))/autocomplete/(?P<to_applabel>[^/]+)/(?P<to_model>[^/]+)/$', 'colonialismdb.common.views.autocomplete'),
    (r'^admin/(?P<from_applabel>[^/]+)/(?P<from_model>[^/]+)/(?P<from_id>\d+)/get_label/(?P<to_applabel>[^/]+)/(?P<to_model>[^/]+)/$', 'colonialismdb.common.views.get_label'),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^static/sources/(?P<path>.+)\.(?P<ext>.+)', 'colonialismdb.sources.views.open_src_file'),

    (r'^databrowse/(.*)', login_required(databrowse.site.root)),
)

if settings.DEBUG:
  urlpatterns += patterns('',
      (r'^static/(?P<path>sources/.+)$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT }),
  )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

colonialismdb/common/forms.py
from django import forms
from django.forms.fields import MultipleChoiceField
from constants import EMPIRE_CHOICES, NATION_STATE_CHOICES, CONTINENT_CHOICES, \
                        SEMI_SOVEREIGN_CHOICES, NON_SOVEREIGN_CHOICES, SOURCE_TYPE_CHOICES, \
                        CONFEDERATION_CHOICES

class GeneralSearchForm(forms.Form):

    start_date_day = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:30px', 'disabled': 'true'}))
    start_date_month = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:30px', 'disabled': 'true'}))
    start_date_year = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:50px', 'disabled': 'true'}))

    end_date_day = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:30px', 'disabled': 'true'}))
    end_date_month = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:30px', 'disabled': 'true'}))
    end_date_year = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'width:50px', 'disabled': 'true'}))
    all_time_frames = forms.BooleanField(initial=True)

    locations = forms.CharField(required=False, widget=forms.TextInput(attrs={'style': 'width:400px', 'disabled': 'true'}))
    all_locations = forms.BooleanField(initial=True)

    continent = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=CONTINENT_CHOICES, initial=('', 'All'))

    empire = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=EMPIRE_CHOICES, initial=('', 'All'))

    nation_state = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=NATION_STATE_CHOICES, initial=('', 'All'))

    semi_sovereign = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=SEMI_SOVEREIGN_CHOICES, initial=('', 'All'))

    non_sovereign = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=NON_SOVEREIGN_CHOICES, initial=('', 'All'))

    source_type = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=SOURCE_TYPE_CHOICES, initial=('', 'All'))

    
    confederation = forms.MultipleChoiceField(required=False,
                                       widget=forms.SelectMultiple(attrs={'size':'8', 'style':'width:200px;'}),
                                       choices=CONFEDERATION_CHOICES, initial=('', 'All'))

colonialismdb/government/forms.py
from django import forms

from common.forms import GeneralSearchForm

class GovernmentSearchForm(GeneralSearchForm):
    test_input = forms.IntegerField(required=False)

colonialismdb/population/forms.py
from django import forms

import models

class MainPopulationQueryForm(forms.Form):
  location = forms.ModelMultipleChoiceField(queryset = models.Location.objects, required = False, label = 'Location')
  begin_date = forms.DateField(required = False, label = "From Date")
  end_date = forms.DateField(required = False, label = "To Date")
  count_type = forms.MultipleChoiceField(required = False, label = "Count Type", choices = (('all', 'All'), ('individ', 'Individuals'), ('fam', 'Families'), ('males', 'Males'), ('females', 'Females')), initial = 'all', widget = forms.CheckboxSelectMultiple)

colonialismdb/economics/views.py
from django.shortcuts import render_to_response
from economics.models import *
from django.db.models import Q
from django.contrib import auth
from django.http import *
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from sources.models import *

# Imports for the Ajax calls and the Jquery autocomplete plugin
from django.http import HttpResponse
from django.utils import simplejson
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

# Imports to aid in unicode string handling
from django.utils.encoding import smart_str, smart_unicode

from government.forms import GovernmentSearchForm


# Ajax call from template picks up matching locations with this function
def locationlookup(request):
    lresults = []
    temp = []
    if request.method == "GET":
        if request.GET.has_key(u'q'):
            value = request.GET[u'q']
            model_results = AggregateTradeDataEntry.objects.filter(location__name__istartswith="%s" % value).select_related().distinct()
            for x in AggregateTradeDataEntry.objects.filter(location__name__istartswith=value).distinct():
                if smart_str(x.location.location.name) not in lresults:
                    lresults.append(smart_str(x.location.location.name))

    json = simplejson.dumps(lresults)
    return HttpResponse(json, mimetype='application/json')


# Search function for Economics data
@login_required
def econsearch(request):
    if request.GET.get('search'):
        form = GovernmentSearchForm(request.GET)
        search = request.GET.get('search')

        startdate = ''
        enddate = ''

        if 'all_time_frames' not in request.GET:
            startdate = "%s-%s-%s" % (request.GET.get('start_date_year'),
                                      request.GET.get('start_date_month'),
                                      request.GET.get('start_date_day'))
            enddate = "%s-%s-%s" % (request.GET.get('end_date_year'),
                                      request.GET.get('end_date_month'),
                                      request.GET.get('end_date_day'))

        if request.GET.get('sourceinput'):
            sourceinput = request.GET.get('sourceinput')
        else:
            sourceinput = ""
        locations_list = []
        results = []

        if startdate:
            datesourceresults = AggregateTradeDataEntry.objects.filter(Q(begin_date__range=(startdate,enddate)) | Q(end_date__range=(startdate,enddate))).filter(Q(source__name__icontains=sourceinput)).select_related().order_by('id')
        else:
            datesourceresults = AggregateTradeDataEntry.objects.filter(Q(source__name__icontains=sourceinput)).select_related().order_by('id')

        if request.GET.get('locations'):
            searchlocations = request.GET.get('locations')
            locations_list = searchlocations.split(", ")
            for x in locations_list:
                for y in datesourceresults.filter(location__name="%s"%x).select_related().order_by('id'):
                    results.append(y)
        else:
            searchlocations=""
            results = datesourceresults
            
        paginator = Paginator(results,20)
        try:
            page = request.GET.get('page','1')
        except ValueError:
            page = 1
        try:
            results = paginator.page(page)
        except (EmptyPage, InvalidPage):
            results = paginator.page(paginator.num_pages)
            
        return render_to_response("economics_search_results.html",
            {
                "locations_list":locations_list,
                "searchlocations":searchlocations,
                "startdate":startdate,
                "enddate":enddate,
                "sourceinput":sourceinput,
                "results":results,
                "search":search,
                "form": form,
                "paginator": paginator,
            },context_instance=RequestContext(request))
    
    else:
        form = GovernmentSearchForm()
        results = []
        locations_list = []
        searchlocations = ""
        startdate = ""
        enddate = ""
        sourceinput = ""
        search = ""
    return render_to_response("economics.html",
            {
                "locations_list":locations_list,
                "searchlocations":searchlocations,
                "startdate":startdate,
                "enddate":enddate,
                "sourceinput":sourceinput,
                "results":results,
                "search":search,
                "form": form,
        },context_instance=RequestContext(request))












"""
    locations_list = []
    for x in AggregateTradeDataEntry.objects.select_related():
        if not x.location.location.name in locations_list:
            locations_list.append(str(x.location.location.name))
    if request.GET.get('datesearch'):
        datesearch = request.GET.get('datesearch')
        startdate = request.GET.get('startdate')
        enddate = request.GET.get('enddate')
        qset = (Q(begin_date__range=(startdate,enddate)) | Q(end_date__range=(startdate,enddate)))
        dateresults = AggregateTradeDataEntry.objects.filter(qset).select_related().order_by('id')
        paginator = Paginator(dateresults,1)
        try:
            page = int(request.GET.get('page',1))
        except ValueError:
            page = 1
        try:
            dateresults = paginator.page(page)
        except (EmptyPage, InvalidPage):
            dateresults = paginator.page(paginator.num_pages)
    else:
        datesearch = ""
        startdate = ""
        enddate = ""
        dateresults = []
    if request.GET.get('locationsearch'):
        locationsearch = request.GET.get('locationsearch')
        searchlocations = request.GET.get("locations")
        if searchlocations:
            loclist = searchlocations.split(", ")
            qs = ""
            locresults = []
            for x in loclist:
                locresults += AggregateTradeDataEntry.objects.filter(Q(location__name="%s" % x)).select_related().order_by('id')
            paginator = Paginator(locresults,1)
            try:
                page = request.GET.get('page','1')
            except ValueError:
                page = '1'
            try:
                locresults = paginator.page(page)
            except (EmptyPage, InvalidPage):
                locresults = paginator.page(paginator.num_pages)
    else:
        searchlocations = ""
        locationsearch = ""
        locresults = []
    if request.GET.get('sourcesearch'):
        sourcesearch = request.GET.get('sourcesearch')
        sourceinput = request.GET.get('sourceinput')
        sourceresults = AggregateTradeDataEntry.objects.select_related().filter(Q(source__name__icontains=sourceinput)).order_by('id')
        paginator = Paginator(sourceresults,1)
        try:
            page = request.GET.get('page','1')
        except ValueError:
            page = '1'
        try:
            sourceresults = paginator.page(page)
        except (EmptyPage, InvalidPage):
            sourceresults = paginator.page(paginator.num_pages)
    else:
        sourcesearch = ""
        sourceinput = ""
        sourceresults = []
        
    return render_to_response("economics.html",{"locations_list":locations_list,"searchlocations":searchlocations,"locresults":locresults,"locationsearch":locationsearch,"datesearch":datesearch,"startdate":startdate,"enddate":enddate,"dateresults":dateresults,"sourcesearch":sourcesearch,"sourceinput":sourceinput,"sourceresults":sourceresults})
    
"""

"""
def test(request):
    resp = []
    return HttpResponse(resp)

def testing(request):
    locations_list = []
    for x in AggregateTradeDataEntry.objects.select_related():
        if not x.location.location.name in locations_list:
            locations_list.append(str(x.location.location.name))
    return render_to_response("test.html",{"locations_list":locations_list})
"""

colonialismdb/templates/about.html
{% extends 'base.html' %}
{% block feature %}
<div id="feature" style='height: 180px;'>
    <div id="feature-content">
        <h1>Welcome to the CLIO World Tables</h1>
        <p>
        </p>
    </div>
</div><!-- /#feature -->
{% endblock %}


{% block extra-content %}
<div id="extra-content">
<p>
    The following folks have been involved in the creation of the CLIO World Tables:
<h1 style='font-size: 16px;'>Project Directors</h1>
    <ul style="margin-left: 5px;list-style-type:none">
        <li style="font-size: 14px;margin-left: 20px;margin-top: 10px;line-height: 16px;">
            John Gerring, Professor, Department of Political Science, Boston University: jgerring at bu dot edu
        </li>
        <li style="font-size: 14px;margin-left: 20px;margin-top: 10px;line-height: 16px;">
            James Mahoney, Professor, Department of Political Science and Sociology, Northwestern University: james-mahoney at northwestern dot edu
        </li>
    </ul>

    <h1 style='font-size: 16px;margin-top: 15px;'>Project Manager</h1>
    <ul style="margin-left: 5px;list-style-type:none">
        <li style="font-size: 14px;margin-left: 20px;margin-top: 10px;line-height: 16px;">
            Natalie Lam:  send.to.natalie at gmail dot com
        </li>
    </ul>

    <h1 style='font-size: 16px;margin-top: 15px;'>Database Manager</h1>
    <ul style="margin-left: 5px;list-style-type:none">
        <li style="font-size: 14px;margin-left: 20px;margin-top: 10px;line-height: 16px;">
            Karim Nagib – PhD candidate, Department of Economics, Boston University: karimn at bu dotedu
        </li>
    </ul>

    <h1 style='font-size: 16px;margin-top: 15px;'>Web Development</h1>
    <ul style="margin-left: 5px;list-style-type:none">
        <li style="font-size: 14px;margin-left: 20px;margin-top: 10px;line-height: 16px;">
            Michael Trosen: mrtrosen@lab305.com
        </li>
    </ul>

<p>

</div>
{% endblock %}

colonialismdb/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="CLIO Database" />
<title>CLIO World Tables</title>
<link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}css/masters.css" />
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}/css/ie.css" />
<![endif]-->
<link rel="stylesheet" media="screen" type="text/css" href="{{ STATIC_URL }}css/jquery.autocomplete.css" />
<script type="text/javascript" src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js" type="text/javascript"></script>
<script src="http://jquery.bassistance.de/autocomplete/jquery.autocomplete.js" type="text/javascript"></script>
	<link rel="stylesheet" media="screen" type="text/css" href="{{ STATIC_URL }}css/peanut.css" />
{% block extra_head %}

{% endblock %}

</head>
<body>

<div id="wrapper">
	<div id="header">
		<h1 id="masthead" style='font-size: 22px;'>
		    CLIO World Tables
		</h1>
		<ul id="audience">
        {% if user.is_authenticated %}
            <li><a href="/accounts/logout/">Logout</a></li>
        {% else %}
            <li><a href="/accounts/login/">Sign In</a></li>
            <li><a href="/accounts/register/">Register</a></li>
        {% endif %}
		<li><a href="{% url about %}">About</a></li>
		<li><a href="{% url about %}">Team</a></li>
		</ul>
		<div id="nav-bar">
			<ul id="nav">
			    <li id="admissions"><a href="{% url government %}">Politics</a></li>
			    <li id="academics"><a href="{% url education %}">Education</a></li>
			    <li id="research"><a href="{% url population %}">Demographics/Health</a></li>
			    <li id="campuslife"><a href="{% url economics %}">Economnics</a></li>
			    <li id="offices"><a href="{% url infrastructure %}">Infrastructure</a></li>
			    <li></li>
            </ul>
        </div><!-- /#nav -->
        {% block feature %}
        <div id="feature" style='height: 300px;'>
            <div id="feature-content">
                <h1>Base HTML</h1>
                feature content
            </div>
        </div><!-- /#feature -->
        {% endblock %}
    </div><!-- /#header -->
        {% block extra-content %}
        <div id="extra-content">
            Extra content
        </div>
        {% endblock %}
	<div id="footer">
		<ul>
		<li><a href="#">&#169; Copyright</a></li>
		<li><a href="{% url about %}">About</a></li>
		<li><a href="{% url about %}">Team</a></li>
		</ul>
	</div><!-- /#footer -->
</div><!-- /#wrapper -->
    </body>
</html>

colonialismdb/templates/education.html
{% extends 'base.html' %}
{% block extra_head %}

<style>
.info{
    padding-top: 0px;padding-bottom: 0px;
    margin-top: 0px;
}
</style>

    <script>
$(document).ready(function(){
    $('#id_all_time_frames').change(function () {
        if ($(this).attr("checked")) {
            // set all the date inputs to disabled
            $("#id_start_date_day").attr("disabled", "disabled");
            $("#id_start_date_month").attr("disabled", "disabled");
            $("#id_start_date_year").attr("disabled", "disabled");
            $("#id_end_date_day").attr("disabled", "disabled");
            $("#id_end_date_month").attr("disabled", "disabled");
            $("#id_end_date_year").attr("disabled", "disabled");
            $("#id_start_date_day").val("");
            $("#id_start_date_month").val("");
            $("#id_start_date_year").val("");
            $("#id_end_date_day").val("");
            $("#id_end_date_month").val("");
            $("#id_end_date_year").val("");
            return;
        }
        $("#id_start_date_day").removeAttr("disabled");
        $("#id_start_date_month").removeAttr("disabled");
        $("#id_start_date_year").removeAttr("disabled");
        $("#id_end_date_day").removeAttr("disabled");
        $("#id_end_date_month").removeAttr("disabled");
        $("#id_end_date_year").removeAttr("disabled");
        $("#id_start_date_day").val("1");
        $("#id_start_date_month").val("1");
        $("#id_start_date_year").val("");
        $("#id_end_date_day").val("1");
        $("#id_end_date_month").val("1");
        $("#id_end_date_year").val("");
    });

    $('#id_all_locations').change(function () {
        if ($(this).attr("checked")) {
            $("#id_locations").attr("disabled", "disabled");
            $("#id_locations").val("");
            return;
        }
        $("#id_locations").removeAttr("disabled");
        $("#id_locations").val("");

    });

});
</script>

{% endblock %}

{% block feature %}
<div id="feature" style='height:50px;'>
    <div id="feature-content">
        <h1>Education Search</h1>
        <p>
        </p>
    </div>
</div><!-- /#feature -->
{% endblock %}


{% block extra-content %}
<div id="extra-content">
		<form action='{% url education %}' method="GET">
        <table id='gov_search_table' style="border: solid 1px #FFF;">
            <tr>
                <th colspan='8' style='text-align: center;'>
                    <h2>Date Parameters</h2>
                    Selecting a start or end date is optional.  If you do not select a date or date range we will return results for all time periods.
                </th>
            </tr>
            <tr>
                <th>Start Date</th>
                <td>
                    {{ form.start_date_day }}
                </td>
                <td>
                    {{ form.start_date_month }}
                </td>
                <td>
                    {{ form.start_date_year }}
                </td>
                <th>End Date</th>
                <td>
                    {{ form.end_date_day }}
                </td>
                <td>
                    {{ form.end_date_month }}
                </td>
                <td>
                    {{ form.end_date_year }}
                    &nbsp;
                    {{  form.all_time_frames }} Don't limit by time
                </td>
            </tr>
            <tr>
                <th>
                </th>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Day
                    </span>
                </td>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Month
                    </span>
                </td>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Year (yyyy)
                    </span>
                </td>
                <th>
                </th>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Day
                    </span>
                </td>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Month
                    </span>
                </td>
                <td class='info'>
                    <span style='font-size: 8px; text-align:center;'>
                        Year (yyyy)
                    </span>
                </td>
            </tr>
            <tr>
                <th>{{ form.source.label }}</th>
                <td colspan='3'>
                    {{ form.source }}
                </td>
                <th></th>
                <td colspan='3'>
                </td>
            </tr>
            <tr>
                <tr>
                    <th colspan='8' style='text-align: center;'>
                        <h2>Political Units</h2>
                        You can limit your search results by any or all of the below parameters.<br />
                        Start typing in the loction entry box and matching locations will auto-appear for you to select from.
                    </th>
                </tr>
                <tr>
                    <th colspan='1'>
                        Location
                    </th>
                    <th colspan='7'>
                        {{  form.locations }}
                        &nbsp;
                        {{  form.all_locations }} All Locations
                        <script>
                            $(function(){
                                function formatItem(row) {
                                    return row;
                                }
                                function formatResult(row) {
                                    //return row.replace(/(<.+?>)/gi, '');
                                    return row
                                }

                                $("#id_locations").autocomplete('{% url government.views.locationlookup %}', {
                                    width: 320,
                                    max: 100,
                                    cacheLength: 10,
                                    highlight: false,
                                    multiple: true,
                                    multipleSeparator: ", ",
                                    scroll: true,
                                    scrollHeight: 300,
                                    dataType: 'json',
                                    formatItem: formatItem,
                                    formatResult: formatResult,
                                    parse: function(data) {
                                            return $.map(data, function(row) {
                                                return { data:row, value:row, result:row };
                                            });
                                        }}).result(
                                            function(e, row, data) {
                                                $("#locations").val = row;
                                            });
                                        $("#sourceentry").css("left","-20%");
                                });
                        </script>
                    </th>
                </tr>
            <tr>
                <td colspan='4' style='text-align: center;'><h2>Sovereign States</h2></td>
                <td colspan='4' style='text-align: center;'><h2>Sub-State Units</h2></td>
            </tr>
            <tr>
                <td colspan='2' style='text-align: center;'>Empires</td>
                <td colspan='2' style='text-align: center;'>Nation-States</td>
                <td colspan='2' style='text-align: center;'>Semi-Sovereign</td>
                <td colspan='2' style='text-align: center;'>Non-Sovereign</td>
            </tr>
            <tr>
                <td colspan='2' style='text-align: center;'>
                    {{  form.empire }}
                </td>
                <td colspan='2' style='text-align: center;'>
                    {{  form.nation_state }}
                </td>
                <td colspan='2' style='text-align: center;'>
                    {{  form.semi_sovereign }}
                </td>
                <td colspan='2' style='text-align: center;'>
                    {{  form.non_sovereign }}
                </td>
            </tr>
            <tr>
                <td colspan='2' style='text-align: center;'>Continent</td>
                <td colspan='2' style='text-align: center;'>Source Type</td>
                <td colspan='2' style='text-align: center;'></td>
                <td colspan='2' style='text-align: center;'><!--Confederation--></td>
            </tr>
            <tr>
                <td colspan='2' style='text-align: center;'>
                    {{  form.continent }}
                </td>
                <td colspan='2' style='text-align: center;'>
                    {{  form.source_type }}
                </td>
                <td colspan='2' style='text-align: center;'>
                </td>
                <td colspan='2' style='text-align: center;'>
                    <!--{{  form.confederation }}-->
                </td>
            </tr>
            <tr>
                <td colspan='8' style='text-align: center;'>&nbsp;
                    <h2>Show results from one of the following categories</h2>
                </td>
            </tr>
            <tr>
                <th colspan='1'>
                    &nbsp;
                </th>
                <th colspan='3'>
                    <input type='radio' name='dataset' value='schools_number_of'> Schools, number of<br />
                    <input type='radio' name='dataset' value='students_number_of'> Students, number of<br />
                    <input type='radio' name='dataset' value='teachers_number_of'> Teachers, number of<br />
                </th>
                <th colspan='4'>
                </th>
            </tr>
            <tr>
                <td colspan='8' style='text-align: right;'>
                    <input type='submit' name='search' value='Search' />
                </td>
            </tr>
        </table>
		</form>
		</div>
	{% endblock %}